name: CI/CD Pipeline

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-release:
    runs-on: self-hosted

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f "C:\Users\JoaoSimino\source\repos\credit-scoring-ui\Docker\Dockerfile" -t ${{ secrets.DOCKERHUB_USERNAME }}/apigateway-api:latest "C:\Users\JoaoSimino\source\repos\credit-scoring-ui"


      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/apigateway-api:latest 