name: CI/CD Pipeline

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-release:
    runs-on: self-hosted

    env:
      DOTNET_VERSION: '8.0.x'
      ASPNETCORE_ENVIRONMENT: 'Test' 

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Mostrar diretório atual
        run: pwd

      - name: Build Docker image
        run: docker build -f Docker/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/apigateway-api:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/apigateway-api:latest 